# Generated by Django 5.0.4 on 2024-05-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='click',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='click',
            name='user_agent_string',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='click',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
