# Generated by Django 5.0.4 on 2024-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_remove_click_user_agent_click_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
