# Generated by Django 5.0.4 on 2024-05-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_click_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='clicks',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
