# Generated by Django 5.0.4 on 2024-05-15 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_remove_click_clicks_shorturl_click_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='click',
            name='device',
        ),
        migrations.RemoveField(
            model_name='click',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='click',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='click',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='referer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
