# Generated by Django 5.0.6 on 2024-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0007_remove_shorturl_click_count_click_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
