# Generated by Django 5.0.6 on 2024-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
