# Generated by Django 5.0.6 on 2024-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_like_unique_together_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
