# Generated by Django 5.0.6 on 2024-06-17 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_userbusinesscard_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesscard',
            name='custom_template_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_templates/'),
        ),
        migrations.AlterField(
            model_name='userbusinesscard',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_card.businesscardtemplate'),
        ),
    ]
