# Generated by Django 5.0.6 on 2024-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
