# Generated by Django 5.0.6 on 2024-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='font_style',
            field=models.CharField(choices=[('font1', 'Font 1'), ('font2', 'Font 2'), ('font3', 'Font 3'), ('font4', 'Font 4'), ('font5', 'Font 5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='layout',
            field=models.CharField(choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3'), ('layout4', 'Layout 4'), ('layout5', 'Layout 5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='theme',
            field=models.CharField(choices=[('theme1', 'Theme 1'), ('theme2', 'Theme 2'), ('theme3', 'Theme 3'), ('theme4', 'Theme 4'), ('theme5', 'Theme 5'), ('theme6', 'Theme 6'), ('theme7', 'Theme 7'), ('theme8', 'Theme 8')], max_length=50),
        ),
    ]
