# Generated by Django 5.0.6 on 2024-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_alter_landingpage_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='background_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='font_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='layout',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='text_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='theme',
            field=models.CharField(max_length=100),
        ),
    ]
