# Generated by Django 5.0.6 on 2024-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0003_alter_landingpage_font_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='bussiness_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='welMessage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
